apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-web-app
  template:
    metadata:
      labels:
        app: demo-web-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: demo-web-app
        image: jfbilodeau.azurecr.io/demos/demo-web-app
        env:
        - name: Message
          value: "Hello from AKS!"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: demo-web-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demo-web-app